language: haskell

ghc:
  - '7.10'

before_install:
  - ghc-pkg list
  
install:
  - cabal install --dependencies-only --enable-tests
  # add -flib-Werror if desired at a later point
  - cabal configure --enable-tests
  
script:
  - cabal build && cabal test
  
